---
title: "data manipulation"
author: "Shiyu KANG"
date: "2026-09-22"
output: github_document
editor_options: 
  chunk_output_type: console
---

This data is for doing data import.

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

Import first ds
```{r}
litters_df = 
  read_csv(
    file = "data/FAS_litters.csv",
    na = c("", "NA", ".")
  )

litters_df = janitor::clean_names(litters_df)
```

Import second ds
```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv",
    skip = 3,
    na = c("","NA",".")
  )

pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or tail
```{r}
head(litters_df, 20)

tail(pups_df, 5)
```


Skimming?

```{r}
skimr::skim(pups_df)
```


## Excel

Jenny Bryan made "readxl" to solve our problems.

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

```{r}
mlb_df
```

Import FOTR words

```{r}
  fotr_df = readxl::read_excel(
    path = "data/LotR_Words.xlsx",
    range = "B3:D6"
  )

fotr_df
```

Two Towers
```{r}
  fotr_df1 = readxl::read_excel(
    path = "data/LotR_Words.xlsx",
    range = "F3:H6"
  )
fotr_df1
```


## Import SAS

read in the PULSE dataset

```{r}
pulse_df = 
  read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```

Import pups with "read.csv()"

```{r}
pups_df_base = 
  read.csv("data/FAS_pups.csv")

pups_df_base
```

won't show: lazy about variable names; super slow for big dataset